{
 "title": "VPC Flow Log Dashboard",
 "tags": [ "VPC Flow Logs" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grafana_ip_src",
    "label": "Source IP Address",
    "query": "SELECT DISTINCT src_ip\nFROM netflow.flows_local"
   },
   {
    "name": "grafana_ip_dst",
    "label": "Destination IP Address",
    "query": "SELECT DISTINCT dst_ip\nFROM netflow.flows_local"
   }
  ]
 },
 "panels": [
  { "title": "Pie Chart: Top Talkers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Traffic by Source IPs",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "p7" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsrc_ip,\n\tSUM(bytes) AS total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tsrc_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT\n\t5"
    }
   ]
  },
  {
   "title": "Top Traffic by Destination IPs",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tdst_ip,\n\tSUM(bytes) AS total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tdst_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Total IP Protocols",
   "type": "piechart",
   "description": "Calculate the total number of bytes for each ip_proto in the last 24 hours",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tprotocol,\n\tSUM(bytes) AS total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tprotocol\nORDER BY\n\ttotal_bytes DESC"
    }
   ]
  },
  {
   "title": "Time Series: Traffic / Packet Rate (netflow.flows_local)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Source Interface Traffic Total (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsrc_ip,\n\ttimestamp,\n\tSUM(bytes) AS total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tsrc_ip,\n\ttimestamp\nORDER BY\n  timestamp"
    }
   ]
  },
  {
   "title": "Destination Interface Traffic Total (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tdst_ip,\n\ttimestamp,\n\tSUM(bytes) AS total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tdst_ip,\n\ttimestamp\nORDER BY\n  timestamp"
    }
   ]
  },
  {
   "title": "Source Interface Traffic Total (PPS)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsrc_ip,\n\ttimestamp,\n\tSUM(packets) AS total_packets\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tsrc_ip,\n\ttimestamp\nORDER BY\n  timestamp"
    }
   ]
  },
  {
   "title": "Destination Interface Traffic Total (PPS)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tdst_ip,\n\ttimestamp,\n\tSUM(packets) AS total_packets\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tdst_ip,\n\ttimestamp\nORDER BY\n  timestamp"
    }
   ]
  },
  { "title": "Bar: Top Traffic per Interval", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Traffic Source IP (Bytes)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    src_ip,\n    SUM(bytes) AS total_bytes,\n    SUM(packets) AS total_packets\nFROM\n    netflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n    src_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Top Traffic Destination IP (Bytes)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    dst_ip,\n    SUM(bytes) AS total_bytes,\n    SUM(packets) AS total_packets\nFROM\n    netflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n    dst_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT 10\n"
    }
   ]
  },
  { "title": "SanKey Diagram", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Top Traffic Talkers (24h)",
   "type": "netsage-sankey-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsrc_ip,\n  protocol,\n\tdst_ip,\n\tSUM(bytes) AS total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tsrc_ip,\n  protocol,\n\tdst_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT\n\t5"
    }
   ]
  },
  {
   "title": "GeoMap: Total Traffic by Region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }
  },
  {
   "title": "Traffic Map in VietNam Region by Source",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsrc_geo_latitude,\n\tsrc_geo_longitude,\n\tsrc_ip,\n\tSUM(bytes) AS src_total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_geo_latitude != 0\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tsrc_geo_latitude,\n\tsrc_geo_longitude,\n\tsrc_ip\nORDER BY\n\tsrc_total_bytes DESC\nLIMIT\n\t100\n"
    },
    {
     "rawSql": "SELECT\n\tdst_geo_latitude,\n\tdst_geo_longitude,\n\tdst_ip,\n\tSUM(bytes) AS dst_total_bytes\nFROM\n\tnetflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND dst_geo_latitude != 0\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n\tdst_geo_latitude,\n\tdst_geo_longitude,\n\tdst_ip\nORDER BY\n\tdst_total_bytes DESC\nLIMIT\n\t100\n"
    }
   ]
  },
  {
   "title": "Top Traffic Source IP (Bytes)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    src_ip,\n    SUM(bytes) AS total_bytes,\n    SUM(packets) AS total_packets\nFROM\n    netflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n    src_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top Traffic Destination IP (Bytes)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    dst_ip,\n    SUM(bytes) AS total_bytes,\n    SUM(packets) AS total_packets\nFROM\n    netflow.flows_local\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nGROUP BY\n    dst_ip\nORDER BY\n\ttotal_bytes DESC\nLIMIT 10\n"
    }
   ]
  },
  { "title": "Table: Raw Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Complete VPC Flow Logs (Filtered)",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT * FROM netflow.flows_local \nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\n  AND src_ip IN ($grafana_ip_src) AND dst_ip IN ($grafana_ip_dst)\nORDER BY timestamp DESC LIMIT 1000\n"
    }
   ]
  },
  {
   "title": "Complete VPC Flow Logs (No Filtered)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT * \nFROM netflow.flows_local \nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime\nORDER BY timestamp DESC LIMIT 1000\n"
    }
   ]
  },
  { "title": "Others 2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "flows_local message counter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as \"time\", count(*) \nFROM netflow.flows_local \nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime GROUP BY time ORDER BY time ASC LIMIT 1000"
    }
   ]
  }
 ]
}