-- filepath: sql/schema/03-materialized-views.sql
-- Purpose: Create materialized views for common aggregations
-- Dependencies: flows_local table exists  
-- Usage: Execute after initial data load for best performance

-- TODO: Implement materialized views
-- 
-- Recommended views:
-- 1. Hourly aggregation (SummingMergeTree)
-- 2. Top talkers by day
-- 3. Protocol distribution
-- 4. Port usage summary
--
-- Example hourly view:
-- CREATE MATERIALIZED VIEW IF NOT EXISTS flows_hourly_mv
-- ENGINE = SummingMergeTree()
-- PARTITION BY toYYYYMM(hour)
-- ORDER BY (hour, src_ip, dst_ip)
-- AS SELECT
--     toStartOfHour(timestamp) as hour,
--     src_ip,
--     dst_ip,
--     protocol,
--     sum(bytes) as total_bytes,
--     sum(packets) as total_packets,
--     count() as flow_count
-- FROM flows_local
-- GROUP BY hour, src_ip, dst_ip, protocol;
