-- filepath: sql/schema/04-skip-indexes.sql
-- Purpose: Add skip indexes for performance optimization
-- Dependencies: flows_local table exists
-- Usage: Execute after table creation, before large data loads

-- TODO: Implement skip indexes
--
-- Recommended indexes:
-- 1. Bloom filter for IP lookups (src_ip, dst_ip)
-- 2. MinMax for numeric fields (bytes, packets)
-- 3. Set index for protocol field
--
-- Example bloom filter:
-- ALTER TABLE flows_local ON CLUSTER '{cluster}'
--     ADD INDEX IF NOT EXISTS src_ip_bloom src_ip 
--     TYPE bloom_filter GRANULARITY 4;
--
-- ALTER TABLE flows_local ON CLUSTER '{cluster}'
--     ADD INDEX IF NOT EXISTS dst_ip_bloom dst_ip 
--     TYPE bloom_filter GRANULARITY 4;
--
-- Performance impact: 10-20x faster for point queries
-- Trade-off: Slightly slower inserts, more disk space
